apiVersion: v2
name: otel-metrics-test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - fastapi
  - opentelemetry
  - metrics
  - observability
maintainers:
  - name: SRE Team
    email: sre@invisible.email
